### ISSUE TITLE
[internal] Running tech debt list

### ISSUE THREAD

**Issue by Jkwok0714** [TestaDiMucca/Hoarder-Util#84]
# Description

Non-comprehensive list of jankiness done in the name of MVP. Should be a list of small internal items unlike some larger discrete issues filed separately, like adding validations or error handling.

- [ ] Load data/stats are two calls when getting data
- [ ] No caching and re-writing entire json blob when updating data - may need to have an internal sqlite for better usage
- [ ] Preload can't use imported enum types for some reason
- [ ] Invoke+handle should replace send+on for its superior ability to serialize data
